// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;
using System.Text;

namespace Demo
{
    public readonly record struct Address(
        string Street,
        string City,
        string Zip
    )
    {
        internal static Address Decode(WireReader reader) =>
            new Address(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString()
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Street)) +
            (4 + Encoding.UTF8.GetByteCount(this.City)) +
            (4 + Encoding.UTF8.GetByteCount(this.Zip));

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Street);
            wire.WriteString(this.City);
            wire.WriteString(this.Zip);
        }
    }
}