// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;
using System.Text;

namespace Demo
{
    public readonly record struct AppError(
        int Code,
        string Message
    )
    {
        internal static AppError Decode(WireReader reader) =>
            new AppError(
                reader.ReadI32(),
                reader.ReadString()
            );

        internal int WireEncodedSize() =>
            4 +
            (4 + Encoding.UTF8.GetByteCount(this.Message));

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteI32(this.Code);
            wire.WriteString(this.Message);
        }
    }
}