// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace Demo
{
    [StructLayout(LayoutKind.Sequential)]
    public readonly record struct Color(
        byte R,
        byte G,
        byte B,
        byte A
    )
    {
        internal static Color Decode(WireReader reader) =>
            new Color(
                reader.ReadU8(),
                reader.ReadU8(),
                reader.ReadU8(),
                reader.ReadU8()
            );

        internal int WireEncodedSize() =>
            1 +
            1 +
            1 +
            1;

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteU8(this.R);
            wire.WriteU8(this.G);
            wire.WriteU8(this.B);
            wire.WriteU8(this.A);
        }
    }
}