// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using System.Buffers;
using System.Buffers.Binary;
using System.Text;

namespace Demo
{

    public static class Demo
    {
        public static bool EchoBool(bool v)
        {
            return NativeMethods.EchoBool(v);
        }

        public static bool NegateBool(bool v)
        {
            return NativeMethods.NegateBool(v);
        }

        public static sbyte EchoI8(sbyte v)
        {
            return NativeMethods.EchoI8(v);
        }

        public static byte EchoU8(byte v)
        {
            return NativeMethods.EchoU8(v);
        }

        public static short EchoI16(short v)
        {
            return NativeMethods.EchoI16(v);
        }

        public static ushort EchoU16(ushort v)
        {
            return NativeMethods.EchoU16(v);
        }

        public static int EchoI32(int v)
        {
            return NativeMethods.EchoI32(v);
        }

        public static int AddI32(int a, int b)
        {
            return NativeMethods.AddI32(a, b);
        }

        public static uint EchoU32(uint v)
        {
            return NativeMethods.EchoU32(v);
        }

        public static long EchoI64(long v)
        {
            return NativeMethods.EchoI64(v);
        }

        public static ulong EchoU64(ulong v)
        {
            return NativeMethods.EchoU64(v);
        }

        public static float EchoF32(float v)
        {
            return NativeMethods.EchoF32(v);
        }

        public static float AddF32(float a, float b)
        {
            return NativeMethods.AddF32(a, b);
        }

        public static double EchoF64(double v)
        {
            return NativeMethods.EchoF64(v);
        }

        public static double AddF64(double a, double b)
        {
            return NativeMethods.AddF64(a, b);
        }

        public static nuint EchoUsize(nuint v)
        {
            return NativeMethods.EchoUsize(v);
        }

        public static nint EchoIsize(nint v)
        {
            return NativeMethods.EchoIsize(v);
        }

        public static string EchoString(string v)
        {
            byte[] _vBytes = Encoding.UTF8.GetBytes(v);
            FfiBuf _buf = NativeMethods.EchoString(_vBytes, (UIntPtr)_vBytes.Length);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static string ConcatStrings(string a, string b)
        {
            byte[] _aBytes = Encoding.UTF8.GetBytes(a);
            byte[] _bBytes = Encoding.UTF8.GetBytes(b);
            FfiBuf _buf = NativeMethods.ConcatStrings(_aBytes, (UIntPtr)_aBytes.Length, _bBytes, (UIntPtr)_bBytes.Length);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static uint StringLength(string v)
        {
            byte[] _vBytes = Encoding.UTF8.GetBytes(v);
            return NativeMethods.StringLength(_vBytes, (UIntPtr)_vBytes.Length);
        }

        public static bool StringIsEmpty(string v)
        {
            byte[] _vBytes = Encoding.UTF8.GetBytes(v);
            return NativeMethods.StringIsEmpty(_vBytes, (UIntPtr)_vBytes.Length);
        }

        public static string RepeatString(string v, uint count)
        {
            byte[] _vBytes = Encoding.UTF8.GetBytes(v);
            FfiBuf _buf = NativeMethods.RepeatString(_vBytes, (UIntPtr)_vBytes.Length, count);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static Point EchoPoint(Point p)
        {
            return NativeMethods.EchoPoint(p);
        }

        public static Point MakePoint(double x, double y)
        {
            return NativeMethods.MakePoint(x, y);
        }

        public static Point AddPoints(Point a, Point b)
        {
            return NativeMethods.AddPoints(a, b);
        }

        public static Color EchoColor(Color c)
        {
            return NativeMethods.EchoColor(c);
        }

        public static Color MakeColor(byte r, byte g, byte b, byte a)
        {
            return NativeMethods.MakeColor(r, g, b, a);
        }

        public static Line EchoLine(Line l)
        {
            using var _wire_l = new WireWriter(l.WireEncodedSize());
            l.WireEncodeTo(_wire_l);
            byte[] _lBytes = _wire_l.ToArray();
            FfiBuf _buf = NativeMethods.EchoLine(_lBytes, (UIntPtr)_lBytes.Length);
            try
            {
                return Line.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static Line MakeLine(double x1, double y1, double x2, double y2)
        {
            FfiBuf _buf = NativeMethods.MakeLine(x1, y1, x2, y2);
            try
            {
                return Line.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static double LineLength(Line l)
        {
            using var _wire_l = new WireWriter(l.WireEncodedSize());
            l.WireEncodeTo(_wire_l);
            byte[] _lBytes = _wire_l.ToArray();
            return NativeMethods.LineLength(_lBytes, (UIntPtr)_lBytes.Length);
        }

        public static Rect EchoRect(Rect r)
        {
            using var _wire_r = new WireWriter(r.WireEncodedSize());
            r.WireEncodeTo(_wire_r);
            byte[] _rBytes = _wire_r.ToArray();
            FfiBuf _buf = NativeMethods.EchoRect(_rBytes, (UIntPtr)_rBytes.Length);
            try
            {
                return Rect.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static double RectArea(Rect r)
        {
            using var _wire_r = new WireWriter(r.WireEncodedSize());
            r.WireEncodeTo(_wire_r);
            byte[] _rBytes = _wire_r.ToArray();
            return NativeMethods.RectArea(_rBytes, (UIntPtr)_rBytes.Length);
        }

        public static Person EchoPerson(Person p)
        {
            using var _wire_p = new WireWriter(p.WireEncodedSize());
            p.WireEncodeTo(_wire_p);
            byte[] _pBytes = _wire_p.ToArray();
            FfiBuf _buf = NativeMethods.EchoPerson(_pBytes, (UIntPtr)_pBytes.Length);
            try
            {
                return Person.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static Person MakePerson(string name, uint age)
        {
            byte[] _nameBytes = Encoding.UTF8.GetBytes(name);
            FfiBuf _buf = NativeMethods.MakePerson(_nameBytes, (UIntPtr)_nameBytes.Length, age);
            try
            {
                return Person.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static string GreetPerson(Person p)
        {
            using var _wire_p = new WireWriter(p.WireEncodedSize());
            p.WireEncodeTo(_wire_p);
            byte[] _pBytes = _wire_p.ToArray();
            FfiBuf _buf = NativeMethods.GreetPerson(_pBytes, (UIntPtr)_pBytes.Length);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static Address EchoAddress(Address a)
        {
            using var _wire_a = new WireWriter(a.WireEncodedSize());
            a.WireEncodeTo(_wire_a);
            byte[] _aBytes = _wire_a.ToArray();
            FfiBuf _buf = NativeMethods.EchoAddress(_aBytes, (UIntPtr)_aBytes.Length);
            try
            {
                return Address.Decode(new WireReader(_buf));
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

        public static string FormatAddress(Address a)
        {
            using var _wire_a = new WireWriter(a.WireEncodedSize());
            a.WireEncodeTo(_wire_a);
            byte[] _aBytes = _wire_a.ToArray();
            FfiBuf _buf = NativeMethods.FormatAddress(_aBytes, (UIntPtr)_aBytes.Length);
            try
            {
                return new WireReader(_buf).ReadString();
            }
            finally
            {
                NativeMethods.FreeBuf(_buf);
            }
        }

    }


    [StructLayout(LayoutKind.Sequential)]
    internal struct FfiBuf
    {
        public IntPtr ptr;
        public UIntPtr len;
        public UIntPtr cap;
        public UIntPtr align;
    }


    internal sealed class WireReader
    {
        private readonly byte[] _data;
        private readonly int _length;
        private int _pos;

        internal WireReader(FfiBuf buf)
        {
            if (buf.ptr == IntPtr.Zero)
            {
                _data = Array.Empty<byte>();
                _length = 0;
            }
            else
            {
                _length = checked((int)(nuint)buf.len);
                _data = new byte[_length];
                if (_length > 0) Marshal.Copy(buf.ptr, _data, 0, _length);
            }
            _pos = 0;
        }

        internal bool ReadBool() => ReadU8() != 0;

        internal sbyte ReadI8()
        {
            Require(1, "i8");
            return (sbyte)_data[_pos++];
        }

        internal byte ReadU8()
        {
            Require(1, "u8");
            return _data[_pos++];
        }

        internal short ReadI16() { Require(2, "i16"); var v = BinaryPrimitives.ReadInt16LittleEndian(_data.AsSpan(_pos)); _pos += 2; return v; }
        internal ushort ReadU16() { Require(2, "u16"); var v = BinaryPrimitives.ReadUInt16LittleEndian(_data.AsSpan(_pos)); _pos += 2; return v; }
        internal int ReadI32() { Require(4, "i32"); var v = BinaryPrimitives.ReadInt32LittleEndian(_data.AsSpan(_pos)); _pos += 4; return v; }
        internal uint ReadU32() { Require(4, "u32"); var v = BinaryPrimitives.ReadUInt32LittleEndian(_data.AsSpan(_pos)); _pos += 4; return v; }
        internal long ReadI64() { Require(8, "i64"); var v = BinaryPrimitives.ReadInt64LittleEndian(_data.AsSpan(_pos)); _pos += 8; return v; }
        internal ulong ReadU64() { Require(8, "u64"); var v = BinaryPrimitives.ReadUInt64LittleEndian(_data.AsSpan(_pos)); _pos += 8; return v; }
        internal float ReadF32() { Require(4, "f32"); var v = BinaryPrimitives.ReadSingleLittleEndian(_data.AsSpan(_pos)); _pos += 4; return v; }
        internal double ReadF64() { Require(8, "f64"); var v = BinaryPrimitives.ReadDoubleLittleEndian(_data.AsSpan(_pos)); _pos += 8; return v; }

        // usize/isize travel as 64-bit integers on the wire so the wire
        // layout stays stable across pointer widths.
        internal nint ReadNInt() => (nint)ReadI64();
        internal nuint ReadNUInt() => (nuint)ReadU64();

        internal string ReadString()
        {
            int len = ReadI32();
            if (len == 0) return "";
            if (len < 0) throw new InvalidOperationException("corrupt wire: negative string length");
            Require(len, "string payload");
            string v = Encoding.UTF8.GetString(_data, _pos, len);
            _pos += len;
            return v;
        }

        internal byte[] ReadBytes()
        {
            int len = ReadI32();
            if (len == 0) return Array.Empty<byte>();
            if (len < 0) throw new InvalidOperationException("corrupt wire: negative bytes length");
            Require(len, "bytes payload");
            byte[] v = new byte[len];
            Buffer.BlockCopy(_data, _pos, v, 0, len);
            _pos += len;
            return v;
        }

        private void Require(int n, string kind)
        {
            if (_pos + n > _length) throw new InvalidOperationException("corrupt wire: truncated " + kind);
        }
    }


    internal sealed class WireWriter : IDisposable
    {
        private const int MinCapacity = 16;

        private byte[] _buffer;
        private int _pos;
        private bool _disposed;

        internal WireWriter(int initialCapacity)
        {
            int cap = Math.Max(initialCapacity, MinCapacity);
            _buffer = ArrayPool<byte>.Shared.Rent(cap);
            _pos = 0;
            _disposed = false;
        }

        /// <summary>Copy the written bytes into a fresh managed array.</summary>
        internal byte[] ToArray()
        {
            if (_pos == 0) return Array.Empty<byte>();
            byte[] result = new byte[_pos];
            Buffer.BlockCopy(_buffer, 0, result, 0, _pos);
            return result;
        }

        internal int Position => _pos;

        internal void WriteBool(bool v) { EnsureCapacity(1); _buffer[_pos++] = (byte)(v ? 1 : 0); }
        internal void WriteI8(sbyte v) { EnsureCapacity(1); _buffer[_pos++] = (byte)v; }
        internal void WriteU8(byte v) { EnsureCapacity(1); _buffer[_pos++] = v; }
        internal void WriteI16(short v) { EnsureCapacity(2); BinaryPrimitives.WriteInt16LittleEndian(_buffer.AsSpan(_pos), v); _pos += 2; }
        internal void WriteU16(ushort v) { EnsureCapacity(2); BinaryPrimitives.WriteUInt16LittleEndian(_buffer.AsSpan(_pos), v); _pos += 2; }
        internal void WriteI32(int v) { EnsureCapacity(4); BinaryPrimitives.WriteInt32LittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteU32(uint v) { EnsureCapacity(4); BinaryPrimitives.WriteUInt32LittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteI64(long v) { EnsureCapacity(8); BinaryPrimitives.WriteInt64LittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }
        internal void WriteU64(ulong v) { EnsureCapacity(8); BinaryPrimitives.WriteUInt64LittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }
        internal void WriteF32(float v) { EnsureCapacity(4); BinaryPrimitives.WriteSingleLittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteF64(double v) { EnsureCapacity(8); BinaryPrimitives.WriteDoubleLittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }

        internal void WriteNInt(nint v) => WriteI64((long)v);
        internal void WriteNUInt(nuint v) => WriteU64((ulong)v);

        internal void WriteString(string v)
        {
            int byteCount = Encoding.UTF8.GetByteCount(v);
            WriteI32(byteCount);
            if (byteCount == 0) return;
            EnsureCapacity(byteCount);
            Encoding.UTF8.GetBytes(v, 0, v.Length, _buffer, _pos);
            _pos += byteCount;
        }

        internal void WriteBytes(byte[] v)
        {
            WriteI32(v.Length);
            if (v.Length == 0) return;
            EnsureCapacity(v.Length);
            Buffer.BlockCopy(v, 0, _buffer, _pos, v.Length);
            _pos += v.Length;
        }

        private void EnsureCapacity(int additional)
        {
            if (_pos + additional <= _buffer.Length) return;
            int next = Math.Max(_buffer.Length * 2, _pos + additional);
            byte[] grown = ArrayPool<byte>.Shared.Rent(next);
            Buffer.BlockCopy(_buffer, 0, grown, 0, _pos);
            ArrayPool<byte>.Shared.Return(_buffer);
            _buffer = grown;
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            ArrayPool<byte>.Shared.Return(_buffer);
            _buffer = Array.Empty<byte>();
        }
    }


    internal static class NativeMethods
    {
        private const string LibName = "demo";

        [DllImport(LibName, EntryPoint = "boltffi_free_buf")]
        internal static extern void FreeBuf(FfiBuf buf);

        [DllImport(LibName, EntryPoint = "boltffi_echo_bool")]
        [return: MarshalAs(UnmanagedType.I1)]
        internal static extern bool EchoBool([MarshalAs(UnmanagedType.I1)] bool v);

        [DllImport(LibName, EntryPoint = "boltffi_negate_bool")]
        [return: MarshalAs(UnmanagedType.I1)]
        internal static extern bool NegateBool([MarshalAs(UnmanagedType.I1)] bool v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_i8")]
        internal static extern sbyte EchoI8(sbyte v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_u8")]
        internal static extern byte EchoU8(byte v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_i16")]
        internal static extern short EchoI16(short v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_u16")]
        internal static extern ushort EchoU16(ushort v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_i32")]
        internal static extern int EchoI32(int v);

        [DllImport(LibName, EntryPoint = "boltffi_add_i32")]
        internal static extern int AddI32(int a, int b);

        [DllImport(LibName, EntryPoint = "boltffi_echo_u32")]
        internal static extern uint EchoU32(uint v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_i64")]
        internal static extern long EchoI64(long v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_u64")]
        internal static extern ulong EchoU64(ulong v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_f32")]
        internal static extern float EchoF32(float v);

        [DllImport(LibName, EntryPoint = "boltffi_add_f32")]
        internal static extern float AddF32(float a, float b);

        [DllImport(LibName, EntryPoint = "boltffi_echo_f64")]
        internal static extern double EchoF64(double v);

        [DllImport(LibName, EntryPoint = "boltffi_add_f64")]
        internal static extern double AddF64(double a, double b);

        [DllImport(LibName, EntryPoint = "boltffi_echo_usize")]
        internal static extern nuint EchoUsize(nuint v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_isize")]
        internal static extern nint EchoIsize(nint v);

        [DllImport(LibName, EntryPoint = "boltffi_echo_string")]
        internal static extern FfiBuf EchoString(byte[] v, UIntPtr vLen);

        [DllImport(LibName, EntryPoint = "boltffi_concat_strings")]
        internal static extern FfiBuf ConcatStrings(byte[] a, UIntPtr aLen, byte[] b, UIntPtr bLen);

        [DllImport(LibName, EntryPoint = "boltffi_string_length")]
        internal static extern uint StringLength(byte[] v, UIntPtr vLen);

        [DllImport(LibName, EntryPoint = "boltffi_string_is_empty")]
        [return: MarshalAs(UnmanagedType.I1)]
        internal static extern bool StringIsEmpty(byte[] v, UIntPtr vLen);

        [DllImport(LibName, EntryPoint = "boltffi_repeat_string")]
        internal static extern FfiBuf RepeatString(byte[] v, UIntPtr vLen, uint count);

        [DllImport(LibName, EntryPoint = "boltffi_echo_point")]
        internal static extern Point EchoPoint(Point p);

        [DllImport(LibName, EntryPoint = "boltffi_make_point")]
        internal static extern Point MakePoint(double x, double y);

        [DllImport(LibName, EntryPoint = "boltffi_add_points")]
        internal static extern Point AddPoints(Point a, Point b);

        [DllImport(LibName, EntryPoint = "boltffi_echo_color")]
        internal static extern Color EchoColor(Color c);

        [DllImport(LibName, EntryPoint = "boltffi_make_color")]
        internal static extern Color MakeColor(byte r, byte g, byte b, byte a);

        [DllImport(LibName, EntryPoint = "boltffi_echo_line")]
        internal static extern FfiBuf EchoLine(byte[] l, UIntPtr lLen);

        [DllImport(LibName, EntryPoint = "boltffi_make_line")]
        internal static extern FfiBuf MakeLine(double x1, double y1, double x2, double y2);

        [DllImport(LibName, EntryPoint = "boltffi_line_length")]
        internal static extern double LineLength(byte[] l, UIntPtr lLen);

        [DllImport(LibName, EntryPoint = "boltffi_echo_rect")]
        internal static extern FfiBuf EchoRect(byte[] r, UIntPtr rLen);

        [DllImport(LibName, EntryPoint = "boltffi_rect_area")]
        internal static extern double RectArea(byte[] r, UIntPtr rLen);

        [DllImport(LibName, EntryPoint = "boltffi_echo_person")]
        internal static extern FfiBuf EchoPerson(byte[] p, UIntPtr pLen);

        [DllImport(LibName, EntryPoint = "boltffi_make_person")]
        internal static extern FfiBuf MakePerson(byte[] name, UIntPtr nameLen, uint age);

        [DllImport(LibName, EntryPoint = "boltffi_greet_person")]
        internal static extern FfiBuf GreetPerson(byte[] p, UIntPtr pLen);

        [DllImport(LibName, EntryPoint = "boltffi_echo_address")]
        internal static extern FfiBuf EchoAddress(byte[] a, UIntPtr aLen);

        [DllImport(LibName, EntryPoint = "boltffi_format_address")]
        internal static extern FfiBuf FormatAddress(byte[] a, UIntPtr aLen);
    }
}
