// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace Demo
{
    [StructLayout(LayoutKind.Sequential)]
    public readonly record struct Dimensions(
        double Width,
        double Height
    )
    {
        internal static Dimensions Decode(WireReader reader) =>
            new Dimensions(
                reader.ReadF64(),
                reader.ReadF64()
            );

        internal int WireEncodedSize() =>
            8 +
            8;

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteF64(this.Width);
            wire.WriteF64(this.Height);
        }
    }
}