// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>

using System;

namespace Demo
{
    public readonly record struct Rect(
        Point Origin,
        Dimensions Dimensions
    )
    {
        internal static Rect Decode(WireReader reader) =>
            new Rect(
                Point.Decode(reader),
                Dimensions.Decode(reader)
            );

        internal int WireEncodedSize() =>
            16 +
            16;

        internal void WireEncodeTo(WireWriter wire)
        {
            this.Origin.WireEncodeTo(wire);
            this.Dimensions.WireEncodeTo(wire);
        }
    }
}