import Demo
import Foundation
import XCTest

final class DemoValueTypesTests: XCTestCase {
    func testBuiltinsAndCustomTypesRoundTrip() throws {
        XCTAssertEqual(echoDuration(d: 2.5), 2.5)
        XCTAssertEqual(makeDuration(secs: 3, nanos: 25), 3.000000025)
        XCTAssertEqual(durationAsMillis(d: 2.5), 2_500)

        let instant = Date(timeIntervalSince1970: 1_701_234_567.89)
        XCTAssertEqual(echoSystemTime(t: instant), instant)
        XCTAssertEqual(systemTimeToMillis(t: instant), 1_701_234_567_890)
        XCTAssertEqual(millisToSystemTime(millis: 1_701_234_567_890), instant)

        let uuid = UUID(uuidString: "123e4567-e89b-12d3-a456-426614174000")!
        XCTAssertEqual(echoUuid(id: uuid), uuid)
        XCTAssertEqual(uuidToString(id: uuid), uuid.uuidString.lowercased())

        let url = URL(string: "https://example.com/demo?q=boltffi")!
        XCTAssertEqual(echoUrl(url: url), url)
        XCTAssertEqual(urlToString(url: url), url.absoluteString)

        let email = "ali@example.com"
        XCTAssertEqual(echoEmail(email: email), email)
        XCTAssertEqual(emailDomain(email: email), "example.com")

        let datetime: UtcDateTime = 1_701_234_567_890
        XCTAssertEqual(echoDatetime(dt: datetime), datetime)
        XCTAssertEqual(datetimeToMillis(dt: datetime), 1_701_234_567_890)
    }

    func testPrimitivesStringsBytesAndVectorsRoundTrip() {
        XCTAssertEqual(echoBool(v: true), true)
        XCTAssertEqual(negateBool(v: false), true)
        XCTAssertEqual(echoI8(v: -7), -7)
        XCTAssertEqual(echoU8(v: 255), 255)
        XCTAssertEqual(echoI16(v: -1234), -1234)
        XCTAssertEqual(echoU16(v: 55_000), 55_000)
        XCTAssertEqual(echoI32(v: -42), -42)
        XCTAssertEqual(addI32(a: 10, b: 20), 30)
        XCTAssertEqual(echoU32(v: 4_000_000_000), 4_000_000_000)
        XCTAssertEqual(echoI64(v: -9_999_999_999), -9_999_999_999)
        XCTAssertEqual(echoU64(v: 9_999_999_999), 9_999_999_999)
        XCTAssertEqual(echoF32(v: 3.5), 3.5, accuracy: 1e-6)
        XCTAssertEqual(addF32(a: 1.5, b: 2.5), 4.0, accuracy: 1e-6)
        XCTAssertEqual(echoF64(v: 3.14159265359), 3.14159265359, accuracy: 1e-9)
        XCTAssertEqual(addF64(a: 1.5, b: 2.5), 4.0, accuracy: 1e-9)
        XCTAssertEqual(echoUsize(v: 123), 123)
        XCTAssertEqual(echoIsize(v: -123), -123)

        XCTAssertEqual(echoString(v: "hello 🌍"), "hello 🌍")
        XCTAssertEqual(concatStrings(a: "foo", b: "bar"), "foobar")
        XCTAssertEqual(stringLength(v: "café"), 5)
        XCTAssertEqual(stringIsEmpty(v: ""), true)
        XCTAssertEqual(repeatString(v: "ab", count: 3), "ababab")

        XCTAssertEqual(echoBytes(data: Data([1, 2, 3, 4])), Data([1, 2, 3, 4]))
        XCTAssertEqual(bytesLength(data: Data([9, 8, 7])), 3)
        XCTAssertEqual(bytesSum(data: Data([1, 2, 3, 4])), 10)
        XCTAssertEqual(makeBytes(len: 4), Data([0, 1, 2, 3]))
        XCTAssertEqual(reverseBytes(data: Data([1, 2, 3, 4])), Data([4, 3, 2, 1]))

        XCTAssertEqual(echoVecI32(v: [1, 2, 3]), [1, 2, 3])
        XCTAssertEqual(echoVecI8(v: [-1, 0, 7]), [-1, 0, 7])
        XCTAssertEqual(echoVecU8(v: Data([0, 1, 2, 3])), Data([0, 1, 2, 3]))
        XCTAssertEqual(echoVecI16(v: [-3, 0, 9]), [-3, 0, 9])
        XCTAssertEqual(echoVecU16(v: [0, 10, 20]), [0, 10, 20])
        XCTAssertEqual(echoVecU32(v: [0, 10, 20]), [0, 10, 20])
        XCTAssertEqual(echoVecI64(v: [-5, 0, 8]), [-5, 0, 8])
        XCTAssertEqual(echoVecU64(v: [0, 1, 2]), [0, 1, 2])
        XCTAssertEqual(echoVecIsize(v: [-2, 0, 5]), [-2, 0, 5])
        XCTAssertEqual(echoVecUsize(v: [0, 2, 4]), [0, 2, 4])
        XCTAssertEqual(echoVecF32(v: [1.25, -2.5]), [1.25, -2.5])
        XCTAssertEqual(echoVecF64(v: [1.5, 2.5]), [1.5, 2.5])
        XCTAssertEqual(echoVecBool(v: [true, false, true]), [true, false, true])
        XCTAssertEqual(echoVecString(v: ["hello", "world"]), ["hello", "world"])
        XCTAssertEqual(vecStringLengths(v: ["hi", "café"]), [2, 5])
        XCTAssertEqual(sumVecI32(v: [10, 20, 30]), 60)
        XCTAssertEqual(makeRange(start: 0, end: 5), [0, 1, 2, 3, 4])
        XCTAssertEqual(reverseVecI32(v: [1, 2, 3]), [3, 2, 1])
    }

    func testOptionFunctionsUseCorrectSwiftSurface() {
        XCTAssertEqual(echoOptionalI32(v: 7), 7)
        XCTAssertNil(echoOptionalI32(v: nil))
        XCTAssertEqual(echoOptionalF64(v: 4.5), Optional(4.5))
        XCTAssertNil(echoOptionalF64(v: nil))
        XCTAssertEqual(echoOptionalBool(v: true), true)
        XCTAssertNil(echoOptionalBool(v: nil))
        XCTAssertEqual(unwrapOrDefaultI32(v: 9, fallback: 4), 9)
        XCTAssertEqual(unwrapOrDefaultI32(v: nil, fallback: 4), 4)
        XCTAssertEqual(makeSomeI32(v: 12), 12)
        XCTAssertNil(makeNoneI32())
        XCTAssertEqual(doubleIfSome(v: 8), 16)
        XCTAssertNil(doubleIfSome(v: nil))

        XCTAssertEqual(echoOptionalString(v: "hello"), "hello")
        XCTAssertNil(echoOptionalString(v: nil))
        XCTAssertEqual(isSomeString(v: "x"), true)
        XCTAssertEqual(isSomeString(v: nil), false)

        XCTAssertEqual(echoOptionalPoint(v: Point(x: 1.0, y: 2.0)), Point(x: 1.0, y: 2.0))
        XCTAssertNil(echoOptionalPoint(v: nil))
        XCTAssertEqual(makeSomePoint(x: 3.0, y: 4.0), Point(x: 3.0, y: 4.0))
        XCTAssertNil(makeNonePoint())

        XCTAssertEqual(echoOptionalStatus(v: .active), .active)
        XCTAssertNil(echoOptionalStatus(v: nil))
        XCTAssertEqual(echoOptionalVec(v: [1, 2, 3]), [1, 2, 3])
        XCTAssertNil(echoOptionalVec(v: nil))
        XCTAssertEqual(optionalVecLength(v: [9, 8]), 2)
        XCTAssertNil(optionalVecLength(v: nil))
    }

    func testResultFunctionsUseCorrectSwiftSurface() throws {
        XCTAssertEqual(try safeDivide(a: 10, b: 2), 5)
        assertThrowsMessageContains("division by zero", try safeDivide(a: 1, b: 0))
        XCTAssertEqual(try safeSqrt(x: 9.0), 3.0, accuracy: 1e-9)
        assertThrowsMessageContains("negative input", try safeSqrt(x: -1.0))
        XCTAssertEqual(try parsePoint(s: "1.5, 2.5"), Point(x: 1.5, y: 2.5))
        assertThrowsMessageContains("expected format", try parsePoint(s: "wat"))
        XCTAssertEqual(try alwaysOk(v: 21), 42)
        assertThrowsMessageContains("boom", try alwaysErr(msg: "boom"))

        XCTAssertEqual(resultToString(v: .success(7)), "ok: 7")
        XCTAssertEqual(resultToString(v: .failure(FfiError(message: "bad"))), "err: bad")

        XCTAssertEqual(try checkedDivide(a: 10, b: 2), 5)
        XCTAssertEqual(try checkedSqrt(x: 9.0), 3.0, accuracy: 1e-9)
        XCTAssertEqual(try checkedAdd(a: 2, b: 3), 5)
        XCTAssertEqual(try validateUsername(name: "valid_name"), "valid_name")
        XCTAssertThrowsError(try checkedDivide(a: 1, b: 0))
        XCTAssertThrowsError(try checkedSqrt(x: -1.0))
        XCTAssertThrowsError(try checkedAdd(a: .max, b: 1))
        XCTAssertThrowsError(try validateUsername(name: "ab"))
        XCTAssertThrowsError(try validateUsername(name: String(repeating: "a", count: 21)))
        XCTAssertThrowsError(try validateUsername(name: "has space"))

        XCTAssertEqual(try resultOfOption(key: 4), 8)
        XCTAssertNil(try resultOfOption(key: 0))
        assertThrowsMessageContains("invalid key", try resultOfOption(key: -1))
        XCTAssertEqual(try resultOfVec(count: 3), [0, 1, 2])
        assertThrowsMessageContains("negative count", try resultOfVec(count: -1))
        XCTAssertEqual(try resultOfString(key: 7), "item_7")
        assertThrowsMessageContains("invalid key", try resultOfString(key: -1))
    }

    func testEnumsRecordsAndValueMethodsBehaveCorrectly() throws {
        XCTAssertEqual(echoStatus(s: .active), .active)
        XCTAssertEqual(statusToString(s: .active), "active")
        XCTAssertEqual(isActive(s: .pending), false)
        XCTAssertEqual(echoVecStatus(values: [.active, .pending]), [.active, .pending])

        XCTAssertEqual(Direction(raw: 3), .west)
        XCTAssertEqual(Direction.cardinal(), .north)
        XCTAssertEqual(Direction(fromDegrees: 90.0), .east)
        XCTAssertEqual(Direction.count(), 4)
        XCTAssertEqual(Direction.north.opposite(), .south)
        XCTAssertEqual(Direction.east.isHorizontal(), true)
        XCTAssertEqual(Direction.west.label(), "W")
        XCTAssertEqual(echoDirection(d: .east), .east)
        XCTAssertEqual(oppositeDirection(d: .east), .west)

        let nameFilter = Filter.byName(name: "ali")
        let pointFilter = Filter.byPoints(anchors: [Point(x: 0.0, y: 0.0), Point(x: 1.0, y: 1.0)])
        XCTAssertEqual(echoFilter(f: .none), .none)
        XCTAssertEqual(echoFilter(f: nameFilter), nameFilter)
        XCTAssertEqual(describeFilter(f: nameFilter), "filter by name: ali")
        XCTAssertEqual(describeFilter(f: pointFilter), "filter by 2 anchor points")
        XCTAssertEqual(describeFilter(f: .byTags(tags: ["ffi", "jni"])), "filter by 2 tags")
        XCTAssertEqual(describeFilter(f: .byRange(min: 1.0, max: 5.0)), "filter by range: 1..5")

        let success = ApiResponse.success(data: "ok")
        let redirect = ApiResponse.redirect(url: "https://example.com")
        XCTAssertEqual(echoApiResponse(response: success), success)
        XCTAssertEqual(echoApiResponse(response: redirect), redirect)
        XCTAssertEqual(isSuccess(response: success), true)
        XCTAssertEqual(isSuccess(response: .empty), false)

        XCTAssertEqual(echoPriority(p: .high), .high)
        XCTAssertEqual(priorityLabel(p: .low), "low")
        XCTAssertEqual(isHighPriority(p: .critical), true)
        XCTAssertEqual(isHighPriority(p: .low), false)
        XCTAssertEqual(echoLogLevel(level: .info), .info)
        XCTAssertEqual(shouldLog(level: .error, minLevel: .warn), true)
        XCTAssertEqual(echoVecLogLevel(levels: [.trace, .info, .error]), [.trace, .info, .error])

        let circle = Shape(radius: 5.0)
        XCTAssertEqual(Shape.unitCircle(), Shape.circle(radius: 1.0))
        XCTAssertEqual(Shape(square: 3.0), Shape.rectangle(width: 3.0, height: 3.0))
        XCTAssertEqual(try Shape(tryCircle: 2.0), Shape.circle(radius: 2.0))
        assertThrowsMessageContains("radius must be positive", try Shape(tryCircle: -1.0))
        XCTAssertEqual(Shape.variantCount(), 4)
        XCTAssertEqual(circle.area(), Double.pi * 25.0, accuracy: 1e-6)
        XCTAssertEqual(circle.describe(), "circle r=5")
        XCTAssertEqual(echoShape(s: makeCircle(radius: 2.0)), .circle(radius: 2.0))
        XCTAssertEqual(echoShape(s: makeRectangle(width: 3.0, height: 4.0)), .rectangle(width: 3.0, height: 4.0))
        XCTAssertEqual(echoVecShape(values: [.circle(radius: 2.0), .rectangle(width: 3.0, height: 4.0), .point]).count, 3)

        XCTAssertEqual(echoMessage(m: .text(body: "hello")), .text(body: "hello"))
        XCTAssertEqual(echoMessage(m: .image(url: "https://example.com/image.png", width: 640, height: 480)), .image(url: "https://example.com/image.png", width: 640, height: 480))
        XCTAssertEqual(messageSummary(m: .text(body: "hi")), "text: hi")
        XCTAssertEqual(messageSummary(m: .image(url: "https://example.com/image.png", width: 640, height: 480)), "image: 640x480 at https://example.com/image.png")
        XCTAssertEqual(messageSummary(m: .ping), "ping")

        XCTAssertEqual(echoAnimal(a: .dog(name: "Rex", breed: "Labrador")), .dog(name: "Rex", breed: "Labrador"))
        XCTAssertEqual(echoAnimal(a: .cat(name: "Milo", indoor: true)), .cat(name: "Milo", indoor: true))
        XCTAssertEqual(animalName(a: .fish(count: 5)), "5 fish")
        XCTAssertEqual(animalName(a: .cat(name: "Milo", indoor: true)), "Milo")

        XCTAssertEqual(Point(x: 1.0, y: 2.0), Point(x: 1.0, y: 2.0))
        assertPointEquals(Point.origin(), 0.0, 0.0)
        assertPointEquals(Point(fromPolar: 2.0, theta: .pi / 2.0), 0.0, 2.0, accuracy: 1e-6)
        assertPointEquals(try Point(tryUnit: 3.0, y: 4.0), 0.6, 0.8, accuracy: 1e-6)
        assertThrowsMessageContains("cannot normalize zero vector", try Point(tryUnit: 0.0, y: 0.0))
        XCTAssertEqual(Point(checkedUnit: 2.0, y: 0.0), Point(x: 1.0, y: 0.0))
        XCTAssertEqual(Point(x: 3.0, y: 4.0).distance(), 5.0, accuracy: 1e-6)
        XCTAssertEqual(Point(x: 1.0, y: 2.0).add(other: Point(x: 3.0, y: 4.0)), Point(x: 4.0, y: 6.0))
        XCTAssertEqual(Point.dimensions(), 2)

        XCTAssertEqual(echoPoint(p: Point(x: 1.5, y: 2.5)), Point(x: 1.5, y: 2.5))
        XCTAssertEqual(tryMakePoint(x: 1.0, y: 2.0), Point(x: 1.0, y: 2.0))
        XCTAssertEqual(makePoint(x: 3.0, y: 4.0), Point(x: 3.0, y: 4.0))
        XCTAssertEqual(addPoints(a: Point(x: 1.0, y: 2.0), b: Point(x: 3.0, y: 4.0)), Point(x: 4.0, y: 6.0))
        XCTAssertEqual(echoColor(c: Color(r: 1, g: 2, b: 3, a: 4)), Color(r: 1, g: 2, b: 3, a: 4))
        XCTAssertEqual(makeColor(r: 10, g: 20, b: 30, a: 40), Color(r: 10, g: 20, b: 30, a: 40))
        XCTAssertEqual(echoLine(l: Line(start: Point(x: 1, y: 2), end: Point(x: 5, y: 6))), Line(start: Point(x: 1, y: 2), end: Point(x: 5, y: 6)))
        XCTAssertEqual(makeLine(x1: 0, y1: 0, x2: 3, y2: 4), Line(start: Point(x: 0, y: 0), end: Point(x: 3, y: 4)))
        XCTAssertEqual(lineLength(l: Line(start: Point(x: 0, y: 0), end: Point(x: 3, y: 4))), 5.0, accuracy: 1e-6)
        XCTAssertEqual(echoRect(r: Rect(origin: Point(x: 1, y: 2), dimensions: Dimensions(width: 3, height: 4))), Rect(origin: Point(x: 1, y: 2), dimensions: Dimensions(width: 3, height: 4)))
        XCTAssertEqual(rectArea(r: Rect(origin: Point(x: 0, y: 0), dimensions: Dimensions(width: 3, height: 4))), 12.0, accuracy: 1e-9)
        XCTAssertEqual(echoPolygon(p: Polygon(points: [Point(x: 0, y: 0), Point(x: 1, y: 0)])), Polygon(points: [Point(x: 0, y: 0), Point(x: 1, y: 0)]))
        XCTAssertEqual(makePolygon(points: [Point(x: 0, y: 0), Point(x: 1, y: 0), Point(x: 0.5, y: 1)]).points.count, 3)
        XCTAssertEqual(polygonVertexCount(p: Polygon(points: [Point(x: 0, y: 0), Point(x: 1, y: 1)])), 2)
        assertPointEquals(polygonCentroid(p: Polygon(points: [Point(x: 0, y: 0), Point(x: 2, y: 0), Point(x: 1, y: 3)])), 1.0, 1.0, accuracy: 1e-6)
        XCTAssertEqual(echoTeam(t: Team(name: "QA", members: ["Dave", "Eve"])), Team(name: "QA", members: ["Dave", "Eve"]))
        XCTAssertEqual(makeTeam(name: "Dev Team", members: ["Alice", "Bob", "Charlie"]).members.count, 3)
        XCTAssertEqual(teamSize(t: Team(name: "Ops", members: ["Frank", "Grace", "Heidi", "Ivan"])), 4)
        XCTAssertEqual(echoClassroom(c: Classroom(students: [Person(name: "Charlie", age: 25)])), Classroom(students: [Person(name: "Charlie", age: 25)]))
        XCTAssertEqual(makeClassroom(students: [Person(name: "Alice", age: 20), Person(name: "Bob", age: 22)]).students.count, 2)
        XCTAssertEqual(echoTaggedScores(ts: TaggedScores(label: "set", scores: [1.0, 2.0, 3.0])), TaggedScores(label: "set", scores: [1.0, 2.0, 3.0]))
        XCTAssertEqual(averageScore(ts: TaggedScores(label: "set", scores: [1.0, 2.0, 3.0])), 2.0, accuracy: 1e-9)
        XCTAssertEqual(echoTask(task: Task(title: "ship", priority: .high, completed: false)), Task(title: "ship", priority: .high, completed: false))
        XCTAssertEqual(makeTask(title: "ship", priority: .critical).completed, false)
        XCTAssertEqual(isUrgent(task: Task(title: "ship", priority: .critical, completed: false)), true)
        XCTAssertEqual(echoNotification(notification: Notification(message: "hello", priority: .low, read: false)), Notification(message: "hello", priority: .low, read: false))
        XCTAssertEqual(echoUserProfile(profile: UserProfile(name: "Ali", age: 30, email: "a@example.com", score: 9.5)), UserProfile(name: "Ali", age: 30, email: "a@example.com", score: 9.5))
        XCTAssertEqual(makeUserProfile(name: "Ali", age: 30, email: nil, score: nil), UserProfile(name: "Ali", age: 30, email: nil, score: nil))
        XCTAssertEqual(userDisplayName(profile: UserProfile(name: "Ali", age: 30, email: nil, score: nil)), "Ali")
        XCTAssertEqual(echoSearchResult(result: SearchResult(query: "ffi", total: 3, nextCursor: "next", maxScore: 0.9)), SearchResult(query: "ffi", total: 3, nextCursor: "next", maxScore: 0.9))
        XCTAssertEqual(hasMoreResults(result: SearchResult(query: "ffi", total: 3, nextCursor: "next", maxScore: 0.9)), true)
        XCTAssertEqual(echoPerson(p: Person(name: "Bob", age: 25)), Person(name: "Bob", age: 25))
        XCTAssertEqual(makePerson(name: "Alice", age: 30), Person(name: "Alice", age: 30))
        XCTAssertEqual(greetPerson(p: Person(name: "Charlie", age: 40)), "Hello, Charlie! You are 40 years old.")
        XCTAssertEqual(echoAddress(a: Address(street: "Main", city: "AMS", zip: "1000")), Address(street: "Main", city: "AMS", zip: "1000"))
        XCTAssertEqual(formatAddress(a: Address(street: "Main", city: "AMS", zip: "1000")), "Main, AMS 1000")
    }
}
